initial_acquisitions: 4
total_acquisitions: 50

test_function:
  class_path: GoldsteinPrice

model:
  class_path: GaussianProcess
  init_args:
    kernel_metric:
      class_path: Euclidean
    kernel_profile:
      class_path: Matern
      init_args:
        nu: 2.5 # 5/2
